### ISSUE TITLE
real functionspace giving error in parallel mode(mpirun) using docker image

### ISSUE THREAD

**Issue by ramayzoraiz** [ComputationalPhysiology/simcardems#195]
## Expected Behavior
print("oh no! it worked")

## Actual Behavior
Error at line: cc=df.FunctionSpace(mesh, "R", 0)

Error:   Unable to re-order graph using SCOTCH.
*** Reason:  Error during re-ordering.
*** Where:   This error was encountered inside SCOTCH.cpp.
*** Process: 2
*** 
*** DOLFIN version: 2019.2.0.dev0
*** Git changeset:  8060a84e8ada0df018772497534092727b06bd56

## Steps to Reproduce the Problem

  1. Create python script "xyz.py" and paste folllowing lines:
 ```
 import dolfin as df
comm=df.MPI.comm_world
mesh=df.UnitCubeMesh(comm,5,5,5)
cc=df.FunctionSpace(mesh, "R", 0)
activation = df.Function(cc)
activation.assign(df.Constant(0.2))
print("oh no! it worked")
```

  2. In terminal, type `mpirun -n 4 python3 xyz.py`

## Specifications

  Failed on two docker images:
  ghcr.io/scientificcomputing/fenics-gmsh:jupterlab-2023-04-21
ghcr.io/computationalphysiology/simcardems:latest
  - Platform:
Docker

**Comment by finsberg** [comment]
You could even reduce it to the following example
```python
import dolfin as df

comm = df.MPI.comm_world
mesh = df.UnitCubeMesh(comm, 5, 5, 5)
cc = df.FunctionSpace(mesh, "R", 0)
```

This is not a bug in `simcardems`, but in `dolfin`, so you should open an issue there instead: https://bitbucket.org/fenics-project/dolfin/issues

**Comment by jorgensd** [comment]
This has been fixed.
use `ghcr.io/scientificcomputing/fenics:2023-08-14` or https://github.com/scientificcomputing/packages/pkgs/container/fenics-gmsh/119060949?tag=2023-08-16
