### ISSUE TITLE
Store initial conditions as first datapoint

### ISSUE THREAD

**Issue by IlsevanHerck** [ComputationalPhysiology/simcardems#37]
## Expected Behavior
The first datapoint of each simulation (t=0) should represent the initial conditions (or previous state of the system). 

## Actual Behavior
The first datapoint stored consists of ones and zeros. For example: In a simulation starting from default initial conditions V(t=0) = 0 mV, not -87 mV as would be expected.
The issue becomes even clearer when using the flag `--load_state`: The first value stored is the same at the value at t=0 (1 for lambda and 0 for Ta, V and Ca). However, it does not seem to affect the simulation itself (for example: the voltage used in calculations does not reset to 0mV). 

## Steps to Reproduce the Problem

  1. Run `python3 -m simcardems run -o "results" -T 50`
  2. Run `python3 -m simcardems postprocess "results" --plot-state-traces`
  3. Check the created file _state_traces.png_

## Specifications
The issue is not introduced in post-processing, as the values are assigned from file _results.h5_ and the plot is unaffected by the value of the empty array. 
  - Version of pulse: 
  - Version of FEniCS: 2019.1.0
  - Platform: MacOS
 
![state_traces](https://user-images.githubusercontent.com/19910714/153229543-78438f21-42b0-41df-8e17-3805806d7dda.png)

**Comment by finsberg** [comment]
@IlsevanHerck Can this be closed?
